### ISSUE TITLE
Generate types and transformer functions for custom transformations

### ISSUE THREAD

**Issue by ublubu** [koki/shorthand#16]
A transform on Container:
```
From
  containers:
   - name: master-container
     image: wlan0/postgresql-master:v0.1
     volumeMounts:
      - mountPath: /postgresql
        name: masterPV
To
  containers:
   - name: master-container
     image: wlan0/postgresql-master:v0.1
     mounts:
       - masterPV:/postgresql
```

A transform on Pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: pod1
To
Pod:
  name: pod1
```

A transform on Pod:
```
From
spec:
  affinity:
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            matchExpressions:
              key: type
              operator: eq
              values:
               - t2.micro
To
host_labels: type=t2.micro
```
